In [39]:
import numpy as np

a=np.array([1,2,3])

print(a)

print(a+1) # this will add one to array

b=np.ones(3)

print(b)
print(a-b)

print(a*a)

print(a>b) # returs array of elements with arrayvalueof T or F

print(a,b)

np.array_equal(a,b) # this will return Bool value
print(np.logical_and(a,b))
print(np.logical_or(a,b))

[1 2 3]
[2 3 4]
[ 1.  1.  1.]
[ 0.  1.  2.]
[1 4 9]
[False  True  True]
[1 2 3] [ 1.  1.  1.]
[ True  True  True]
[ True  True  True]


# Logical operators

In [38]:
import numpy as np
a=np.array([1,1,0,1])
b=np.array([0,1,0,1])

print(np.logical_and(a,b))
print(np.logical_or(a,b))

np.sin(a)
np.cos(a)


np.sum(a)

a=np.array([[1,2,3,],[2,2,22]])

print(a.sum(axis=0)) # column wise sum
print(a.sum(axis=1)) # row wise sum

a.min()
a.max()

print(a.argmax()) # gives index of max item
print(a.argmin()) # gives index of min item

print(np.any([True,False])) # returns if atleast one is true
print(np.any([False,False])) # returns if atleast one is true

print(np.any(a>2)) # returns true if contains atleast one element 

[False  True False  True]
[ True  True False  True]
[ 3  4 25]
[ 6 26]
5
0
True
False


In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

((a<=b) & (b<=c)).all() # this will do [T,T,T] & [T,T,T] -> [T,T,T].all()-> Gives True

True

# Statistics

In [43]:
x=np.array([1,2,3])
y=np.array([1,2,3])

print(x.mean())
print(np.median(x))

2.0
2.0


# Load file

In [52]:
data=np.loadtxt('c:\\marks.txt')
print(data)
print(data.T)
print(data)

print(data.std(axis=0))
print(data.std(axis=1))

[[ 10.  20.  30.  40.]
 [ 10.  20.  30.  50.]
 [ 10.  20.  40.  20.]]
[[ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  40.]
 [ 40.  50.  20.]]
[[ 10.  20.  30.  40.]
 [ 10.  20.  30.  50.]
 [ 10.  20.  40.  20.]]
[  0.           0.           4.71404521  12.47219129]
[ 11.18033989  14.79019946  10.89724736]


# Broadcasting 

In [53]:
print(np.tile(np.arange(1,100,10),(3,2)))

[[ 1 11 21 31 41 51 61 71 81 91  1 11 21 31 41 51 61 71 81 91]
 [ 1 11 21 31 41 51 61 71 81 91  1 11 21 31 41 51 61 71 81 91]
 [ 1 11 21 31 41 51 61 71 81 91  1 11 21 31 41 51 61 71 81 91]]
