In [ ]:
# numpy is used for mathematical calucatiions


In [15]:
import numpy as np

print(np.array([1,2,3,4]))  #Creates array out of list

print(np.arange(100))

b=np.array([[1,2,3],[2,3,4]])

print(len(b))
print(b.shape)
print(b.ndim)

print(b)


[1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
2
(2, 3)
2
[[1 2 3]
 [2 3 4]]


# 1d array is called vector
# 2d array is called matrix
# nd array is called tensorflow

In [16]:
np.arange(1,10,2) # start and end and stepsize

array([1, 3, 5, 7, 9])

In [17]:
a=np.linspace(0,1,6)

print(a)

[ 0.   0.2  0.4  0.6  0.8  1. ]


In [21]:
a=np.ones((1,4))
print(a)

[[ 1.  1.  1.  1.]]


# Identity Matrix

eye

In [22]:
np.eye(3,3) # which has diagnol elements as 0

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Diagnol matrix
diag

In [6]:
import numpy as np
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [8]:
print(np.random.rand(5))

[ 0.47397537  0.07828321  0.61198206  0.54164495  0.09818012]


# Float type 

In [9]:
print(np.arange(10,dtype='float'))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [14]:
print(np.array(['test','new']).dtype)
print(np.array([True,False]).dtype)

<U4
bool


# Array Assignment


In [15]:
# a[2,3]=10 as this is a 2d array

# Slicing

In [22]:
a=np.arange(10)
print(a)

print(a[0:4:2]) # start:end(exclusive):stepsize
a[5:]=10
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2]
[ 0  1  2  3  4 10 10 10 10 10]


In [23]:
a=np.arange(10)

b=[1,2,3,3,5]

b[5:]=a[::-1] # copies in reverse order

print(b)

[1, 2, 3, 3, 5, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [29]:
a=10
b=10
b=20
print(a)
print(id(a),id(b))  # normal variables copy

10
498867280 498867440


In [27]:
np.shares_memory(a,b)

False

In [32]:
a=np.arange(10) # from numpy both will shares the same memory
b=a[2:]

print(np.shares_memory(a,b))

print(a,b)

True
[0 1 2 3 4 5 6 7 8 9] [2 3 4 5 6 7 8 9]


In [31]:
b[1]=10  # this will modify a also

print(a)

[ 0  1  2 10  4  5  6  7  8  9]


# Use Copy to copy 

In [35]:
b=a[2:].copy()
print(b)
b[1]=20
print(a)



[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [40]:
mask=(a%2==0)

temp=a[mask]  # these will not create views only deep copy

print(temp)

a[mask]=-1

print(a)

[]
[-1  1 -1  3 -1  5 -1  7 -1  9]
